spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-headers: "*"
            allowed-methods: "*"

      routes:
        - id: saloon_service
          uri: http://localhost:8081
          predicates:
            - Path=/saloons/**
          filters:
            - AuthenticationFilter

        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: order_service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path=/auth/**

  application:
    name: gateway

server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: key_alias

logging:
  level:
    org.springframework.cloud:
      gateway: TRACE
    root: info
logging.level.org.springframework.cloud:
  gateway:
    route:
      RouteDefinitionLocator: INFO
